spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock
    username: dbuser
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL8Dialect
      driverClassName: com.mysql.cj.jdbc.Driver
    database: mysql
    show-sql: true